name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ESP-IDF ${{ matrix.idf_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        idf_version: [v5.3.2, v5.4.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with ESP-IDF ${{ matrix.idf_version }}
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.idf_version }}
          target: esp32
          path: "."
